// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/doer/doer.proto

package doer

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DoAwesomeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DoAwesomeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DoAwesomeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DoAwesomeRequestMultiError, or nil if none found.
func (m *DoAwesomeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DoAwesomeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetInput()); l < 5 || l > 10 {
		err := DoAwesomeRequestValidationError{
			field:  "Input",
			reason: "value length must be between 5 and 10 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DoAwesomeRequestMultiError(errors)
	}

	return nil
}

// DoAwesomeRequestMultiError is an error wrapping multiple validation errors
// returned by DoAwesomeRequest.ValidateAll() if the designated constraints
// aren't met.
type DoAwesomeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DoAwesomeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DoAwesomeRequestMultiError) AllErrors() []error { return m }

// DoAwesomeRequestValidationError is the validation error returned by
// DoAwesomeRequest.Validate if the designated constraints aren't met.
type DoAwesomeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DoAwesomeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DoAwesomeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DoAwesomeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DoAwesomeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DoAwesomeRequestValidationError) ErrorName() string { return "DoAwesomeRequestValidationError" }

// Error satisfies the builtin error interface
func (e DoAwesomeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDoAwesomeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DoAwesomeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DoAwesomeRequestValidationError{}

// Validate checks the field values on DoAwesomeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DoAwesomeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DoAwesomeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DoAwesomeResponseMultiError, or nil if none found.
func (m *DoAwesomeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DoAwesomeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Msg

	if len(errors) > 0 {
		return DoAwesomeResponseMultiError(errors)
	}

	return nil
}

// DoAwesomeResponseMultiError is an error wrapping multiple validation errors
// returned by DoAwesomeResponse.ValidateAll() if the designated constraints
// aren't met.
type DoAwesomeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DoAwesomeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DoAwesomeResponseMultiError) AllErrors() []error { return m }

// DoAwesomeResponseValidationError is the validation error returned by
// DoAwesomeResponse.Validate if the designated constraints aren't met.
type DoAwesomeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DoAwesomeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DoAwesomeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DoAwesomeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DoAwesomeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DoAwesomeResponseValidationError) ErrorName() string {
	return "DoAwesomeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DoAwesomeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDoAwesomeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DoAwesomeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DoAwesomeResponseValidationError{}
